import { SUI_TYPE_ARG } from '@mysten/sui.js/utils';

import { TOKEN_SYMBOL } from '@/lib';
import {
  CoinData,
  CoinDataWithChainInfo,
} from '@/views/pool-details/pool-form/pool-form.types';

import { Network, OBJECT_RECORD } from '.';

export const COIN_METADATA = {
  [SUI_TYPE_ARG]: {
    name: 'Sui',
    decimals: 9,
    symbol: TOKEN_SYMBOL.SUI,
  },
};

export const TESTNET_BASE_COINS = {
  SUI: SUI_TYPE_ARG,
  BNB: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::ibnb::IBNB',
  ETH: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::ieth::IETH',
  BTC: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::ibtc::IBTC',
  USDT: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::iusdt::IUSDT',
  USDC: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::iusdc::IUSDC',
};

export const VOLATILE = {
  [Network.TESTNET]: `${
    OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
  }::curve::Volatile`,
  [Network.MAINNET]: `${
    OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
  }::curve::Volatile`,
};

export const STABLE = {
  [Network.TESTNET]: `${
    OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
  }::curve::Stable`,
  [Network.MAINNET]: `${
    OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
  }::curve::Stable`,
};

export const MAINNET_BASE_COINS = {
  SUI: SUI_TYPE_ARG,
  ETH_WORMHOLE_USDC:
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
  NATIVE_WORMHOLE_ETH:
    '0xaf8cd5edc19c4512f4259f0bee101a40d41ebed738ade5874359610ef8eeced5::coin::COIN',
  ETH_WORMHOLE_USDT:
    '0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c::coin::COIN',
  NATIVE_WORMHOLE_WBNB:
    '0xb848cce11ef3a8f62eccea6eb5b35a12c4c2b1ee1af7755d02d7bd6218e8226f::coin::COIN',
  NATIVE_WORMHOLE_WAVAX:
    '0x1e8b532cca6569cab9f9b9ebc73f8c13885012ade714729aa3b450e0339ac766::coin::COIN',
  NATIVE_WORMHOLE_WFTM:
    '0x6081300950a4f1e2081580e919c210436a1bed49080502834950d31ee55a2396::coin::COIN',
  NATIVE_WORMHOLE_CELO:
    '0xa198f3be41cda8c07b3bf3fee02263526e535d682499806979a111e88a5a8d0f::coin::COIN',
  NATIVE_WORMHOLE_WMATIC:
    '0xdbe380b13a6d0f5cdedd58de8f04625263f113b3f9db32b3e1983f49e2841676::coin::COIN',
  NATIVE_WORMHOLE_SOL:
    '0xb7844e289a8410e50fb3ca48d69eb9cf29e27d223ef90353fe1bd8e27ff8f3f8::coin::COIN',
  BSC_WORMHOLE_ADA:
    '0x4eac6573f65e7db5aea5a23e1335993a57e088dcd4aff7934059d9a6311d8655::coin::COIN',
  BSC_WORMHOLE_BTCB:
    '0x5cc7b6ed0ce0d43d08667793f6efe7a34d678a780755dc37ea8bfa8805f63327::coin::COIN',
  BSC_WORMHOLE_USDT:
    '0x603b488c87e0d1df64560a61418c87238d440a29ee39bbd757b0c92d38a35c7c::coin::COIN',
  BSC_WORMHOLE_USDC:
    '0x909cba62ce96d54de25bec9502de5ca7b4f28901747bbf96b76c2e63ec5f1cba::coin::COIN',
  BSC_WORMHOLE_ETH:
    '0x5029d5a94429a73b8036cd67192d9c5e09bbc2c0fee942d50075a9edba66744f::coin::COIN',
  BSC_WORMHOLE_FLOKI:
    '0xbcbbd5c23edf35fc279e21ebc129a1187dbfa5b086c63a8e7ff202865888b27b::coin::COIN',
  BSC_WORMHOLE_DOGE:
    '0xd399b358bd0e835000f6caa8c771a7d186499b6e62d413c2fd6cfed709689f28::coin::COIN',
  ETH_CELER_WETH:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_weth_coin::CELER_WETH_COIN',
  ETH_CELER_WBTC:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_wbtc_coin::CELER_WBTC_COIN',
  ETH_CELER_USDC:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_usdc_coin::CELER_USDC_COIN',
  ETH_CELER_USDT:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_usdt_coin::CELER_USDT_COIN',
};

export const COIN_TYPE = {
  [Network.TESTNET]: {
    ...TESTNET_BASE_COINS,
    SUID: '0x02871464ed71b80969b32f2b23c981b085866485ba5368c0f59588fcc0dbce47::suid::SUID',
  },
  [Network.MAINNET]: {
    ...MAINNET_BASE_COINS,
  },
};

export const COIN_TYPE_TO_STABLE = {
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].BNB]: false,
    [COIN_TYPE[Network.TESTNET].ETH]: false,
    [COIN_TYPE[Network.TESTNET].BTC]: false,
    [COIN_TYPE[Network.TESTNET].USDT]: true,
    [COIN_TYPE[Network.TESTNET].USDC]: true,
    [COIN_TYPE[Network.TESTNET].SUI]: false,
    [COIN_TYPE[Network.TESTNET].SUID]: true,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]: false,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]: true,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]: true,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]: true,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]: true,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]: false,
  },
};

export const COIN_TYPE_TO_SYMBOL = {
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].BNB]: TOKEN_SYMBOL.BNB,
    [COIN_TYPE[Network.TESTNET].ETH]: TOKEN_SYMBOL.ETH,
    [COIN_TYPE[Network.TESTNET].BTC]: TOKEN_SYMBOL.BTC,
    [COIN_TYPE[Network.TESTNET].USDT]: TOKEN_SYMBOL.USDT,
    [COIN_TYPE[Network.TESTNET].USDC]: TOKEN_SYMBOL.USDC,
    [COIN_TYPE[Network.TESTNET].SUI]: TOKEN_SYMBOL.SUI,
    [COIN_TYPE[Network.TESTNET].SUID]: TOKEN_SYMBOL.SUID,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: TOKEN_SYMBOL.SUI,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]: TOKEN_SYMBOL.ETH,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]: TOKEN_SYMBOL.USDC,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]: TOKEN_SYMBOL.USDT,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]:
      TOKEN_SYMBOL.WORMHOLE_WBNB,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]:
      TOKEN_SYMBOL.WORMHOLE_WAVAX,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]:
      TOKEN_SYMBOL.WORMHOLE_WFTM,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]:
      TOKEN_SYMBOL.WORMHOLE_CELO,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL]: TOKEN_SYMBOL.WORMHOLE_SOL,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]:
      TOKEN_SYMBOL.WORMHOLE_WMATIC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]: TOKEN_SYMBOL.WORMHOLE_ADA,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]: TOKEN_SYMBOL.WORMHOLE_BTCB,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]: TOKEN_SYMBOL.WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]: TOKEN_SYMBOL.WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]: TOKEN_SYMBOL.WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]:
      TOKEN_SYMBOL.WORMHOLE_FLOKI,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]: TOKEN_SYMBOL.WORMHOLE_DOGE,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC]: TOKEN_SYMBOL.ETH_CELER_WBTC,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDC]: TOKEN_SYMBOL.ETH_CELER_USDC,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WETH]: TOKEN_SYMBOL.ETH_CELER_WETH,
  },
};

export const COIN_DECIMALS = {
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].BTC]: 9,
    [COIN_TYPE[Network.TESTNET].ETH]: 9,
    [COIN_TYPE[Network.TESTNET].BNB]: 9,
    [COIN_TYPE[Network.TESTNET].USDT]: 9,
    [COIN_TYPE[Network.TESTNET].USDC]: 9,
    [COIN_TYPE[Network.TESTNET].SUI]: 9,
    [COIN_TYPE[Network.TESTNET].SUID]: 9,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: 9,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]: 8,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]: 6,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]: 6,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]: 8,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WETH]: 9,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC]: 8,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDC]: 6,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDT]: 6,
  },
};

export const COINS: Record<Network, Record<string, CoinData>> = {
  [Network.TESTNET]: {
    ETH: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].ETH],
      symbol: TOKEN_SYMBOL.ETH,
      type: COIN_TYPE[Network.TESTNET].ETH,
    },
    BTC: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].BTC],
      symbol: TOKEN_SYMBOL.BTC,
      type: COIN_TYPE[Network.TESTNET].BTC,
    },
    BNB: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].BNB],
      symbol: TOKEN_SYMBOL.BNB,
      type: COIN_TYPE[Network.TESTNET].BNB,
    },
    SUI: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].SUI],
      symbol: TOKEN_SYMBOL.SUI,
      type: COIN_TYPE[Network.TESTNET].SUI,
    },
    USDC: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].USDC],
      symbol: TOKEN_SYMBOL.USDC,
      type: COIN_TYPE[Network.TESTNET].USDC,
    },
    USDT: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].USDT],
      symbol: TOKEN_SYMBOL.USDT,
      type: COIN_TYPE[Network.TESTNET].USDT,
    },
    SUID: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].SUI],
      symbol: TOKEN_SYMBOL.SUID,
      type: COIN_TYPE[Network.TESTNET].SUID,
    },
  },
  [Network.MAINNET]: {
    SUI: {
      decimals: COIN_DECIMALS[Network.MAINNET][COIN_TYPE[Network.MAINNET].SUI],
      symbol: TOKEN_SYMBOL.SUI,
      type: COIN_TYPE[Network.MAINNET].SUI,
    },
    ETH_WORMHOLE_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_USDC,
      type: COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC,
    },
    NATIVE_WORMHOLE_ETH: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_ETH,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH,
    },
    ETH_WORMHOLE_USDT: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_USDT,
      type: COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT,
    },
    NATIVE_WORMHOLE_WBNB: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_WBNB,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB,
    },
    NATIVE_WORMHOLE_WAVAX: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_WAVAX,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX,
    },
    NATIVE_WORMHOLE_WFTM: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_WFTM,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM,
    },
    NATIVE_WORMHOLE_SOL: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_SOL,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL,
    },
    NATIVE_WORMHOLE_CELO: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_CELO,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO,
    },
    NATIVE_WORMHOLE_WMATIC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_WMATIC,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC,
    },
    BSC_WORMHOLE_ADA: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_ADA,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA,
    },
    BSC_WORMHOLE_BTCB: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_BTCB,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB,
    },
    BSC_WORMHOLE_USDT: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_USDT,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT,
    },
    BSC_WORMHOLE_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_USDC,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC,
    },
    BSC_WORMHOLE_ETH: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_ETH,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH,
    },
    BSC_WORMHOLE_FLOKI: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_FLOKI,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI,
    },
    BSC_WORMHOLE_DOGE: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_DOGE,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE,
    },
    ETH_CELER_WBTC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC
        ],
      symbol: TOKEN_SYMBOL.ETH_CELER_WBTC,
      type: COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC,
    },
    ETH_CELER_WETH: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_CELER_WETH
        ],
      symbol: TOKEN_SYMBOL.ETH_CELER_WETH,
      type: COIN_TYPE[Network.MAINNET].ETH_CELER_WETH,
    },
    ETH_CELER_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_CELER_USDC
        ],
      symbol: TOKEN_SYMBOL.ETH_CELER_USDC,
      type: COIN_TYPE[Network.MAINNET].ETH_CELER_USDC,
    },
    ETH_CELER_USDT: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_CELER_USDT
        ],
      symbol: TOKEN_SYMBOL.ETH_CELER_USDT,
      type: COIN_TYPE[Network.MAINNET].ETH_CELER_USDT,
    },
  },
};

export const COIN_TYPE_TO_COIN = {
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].ETH]: COINS[Network.TESTNET].ETH,
    [COIN_TYPE[Network.TESTNET].BTC]: COINS[Network.TESTNET].BTC,
    [COIN_TYPE[Network.TESTNET].BNB]: COINS[Network.TESTNET].BNB,
    [COIN_TYPE[Network.TESTNET].SUI]: COINS[Network.TESTNET].SUI,
    [COIN_TYPE[Network.TESTNET].USDC]: COINS[Network.TESTNET].USDC,
    [COIN_TYPE[Network.TESTNET].USDT]: COINS[Network.TESTNET].USDT,
    [COIN_TYPE[Network.TESTNET].SUID]: COINS[Network.TESTNET].SUID,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: COINS[Network.MAINNET].SUI,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]:
      COINS[Network.MAINNET].ETH_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]:
      COINS[Network.MAINNET].ETH_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_SOL,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_WBNB,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_WAVAX,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_WFTM,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_CELO,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_WMATIC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]:
      COINS[Network.MAINNET].BSC_WORMHOLE_ADA,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]:
      COINS[Network.MAINNET].BSC_WORMHOLE_BTCB,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]:
      COINS[Network.MAINNET].BSC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]:
      COINS[Network.MAINNET].BSC_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]:
      COINS[Network.MAINNET].BSC_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]:
      COINS[Network.MAINNET].BSC_WORMHOLE_FLOKI,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]:
      COINS[Network.MAINNET].BSC_WORMHOLE_DOGE,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WETH]:
      COINS[Network.MAINNET].ETH_CELER_WETH,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC]:
      COINS[Network.MAINNET].ETH_CELER_WBTC,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDC]:
      COINS[Network.MAINNET].ETH_CELER_USDC,
  },
};

export const STRICT_TOKENS_TYPE: Record<Network, ReadonlyArray<string>> = {
  [Network.TESTNET]: [
    TESTNET_BASE_COINS.SUI,
    TESTNET_BASE_COINS.BNB,
    TESTNET_BASE_COINS.BTC,
    TESTNET_BASE_COINS.ETH,
    TESTNET_BASE_COINS.USDC,
    TESTNET_BASE_COINS.USDT,
  ],
  [Network.MAINNET]: [MAINNET_BASE_COINS.SUI],
};

export const WORMHOLE_TOKENS_TYPE: Record<Network, ReadonlyArray<string>> = {
  [Network.TESTNET]: [],
  [Network.MAINNET]: [
    MAINNET_BASE_COINS.BSC_WORMHOLE_ADA,
    MAINNET_BASE_COINS.BSC_WORMHOLE_BTCB,
    MAINNET_BASE_COINS.BSC_WORMHOLE_DOGE,
    MAINNET_BASE_COINS.BSC_WORMHOLE_ETH,
    MAINNET_BASE_COINS.BSC_WORMHOLE_FLOKI,
    MAINNET_BASE_COINS.BSC_WORMHOLE_USDC,
    MAINNET_BASE_COINS.BSC_WORMHOLE_USDT,
    MAINNET_BASE_COINS.ETH_WORMHOLE_USDC,
    MAINNET_BASE_COINS.ETH_WORMHOLE_USDT,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_CELO,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_ETH,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_SOL,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_WAVAX,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_WBNB,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_WFTM,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_WMATIC,
  ],
};

export const CELER_TOKENS_TYPE: Record<Network, ReadonlyArray<string>> = {
  [Network.TESTNET]: [],
  [Network.MAINNET]: [
    MAINNET_BASE_COINS.ETH_CELER_USDC,
    MAINNET_BASE_COINS.ETH_CELER_USDT,
    MAINNET_BASE_COINS.ETH_CELER_WBTC,
    MAINNET_BASE_COINS.ETH_CELER_WETH,
  ],
};

export const STRICT_TOKENS: Record<Network, Array<CoinData>> = {
  [Network.TESTNET]: [
    COINS[Network.TESTNET].SUI,
    COINS[Network.TESTNET].BNB,
    COINS[Network.TESTNET].BTC,
    COINS[Network.TESTNET].ETH,
    COINS[Network.TESTNET].USDC,
    COINS[Network.TESTNET].USDT,
  ],
  [Network.MAINNET]: [COINS[Network.MAINNET].SUI],
};

export const WORMHOLE_TOKENS: Record<Network, Array<CoinDataWithChainInfo>> = {
  [Network.TESTNET]: [],
  [Network.MAINNET]: [
    COINS[Network.MAINNET].NATIVE_WORMHOLE_ETH,
    { ...COINS[Network.MAINNET].ETH_WORMHOLE_USDC, chain: 'ETH' },
    { ...COINS[Network.MAINNET].ETH_WORMHOLE_USDT, chain: 'ETH' },
    COINS[Network.MAINNET].NATIVE_WORMHOLE_WBNB,
    { ...COINS[Network.MAINNET].BSC_WORMHOLE_USDC, chain: 'BSC' },
    { ...COINS[Network.MAINNET].BSC_WORMHOLE_USDT, chain: 'BSC' },
    { ...COINS[Network.MAINNET].BSC_WORMHOLE_ETH, chain: 'BSC' },
    { ...COINS[Network.MAINNET].BSC_WORMHOLE_ADA, chain: 'BSC' },
    { ...COINS[Network.MAINNET].BSC_WORMHOLE_BTCB, chain: 'BSC' },
    { ...COINS[Network.MAINNET].BSC_WORMHOLE_DOGE, chain: 'BSC' },
    { ...COINS[Network.MAINNET].BSC_WORMHOLE_FLOKI, chain: 'BSC' },
    COINS[Network.MAINNET].NATIVE_WORMHOLE_SOL,
    COINS[Network.MAINNET].NATIVE_WORMHOLE_CELO,
    COINS[Network.MAINNET].NATIVE_WORMHOLE_WAVAX,
    COINS[Network.MAINNET].NATIVE_WORMHOLE_WFTM,
    COINS[Network.MAINNET].NATIVE_WORMHOLE_WMATIC,
  ],
};

export const CELER_TOKENS: Record<Network, Array<CoinDataWithChainInfo>> = {
  [Network.TESTNET]: [],
  [Network.MAINNET]: [
    { ...COINS[Network.MAINNET].ETH_CELER_USDC, chain: 'ETH' },
    { ...COINS[Network.MAINNET].ETH_CELER_USDT, chain: 'ETH' },
    { ...COINS[Network.MAINNET].ETH_CELER_WBTC, chain: 'ETH' },
    { ...COINS[Network.MAINNET].ETH_CELER_WETH, chain: 'ETH' },
  ],
};

export const ALL_TOKENS: Record<
  Network,
  ReadonlyArray<CoinDataWithChainInfo>
> = {
  [Network.TESTNET]: STRICT_TOKENS[Network.TESTNET],
  [Network.MAINNET]: [
    ...STRICT_TOKENS[Network.MAINNET],
    ...WORMHOLE_TOKENS[Network.MAINNET],
    ...CELER_TOKENS[Network.MAINNET],
  ],
};
