import { SUI_TYPE_ARG } from '@mysten/sui.js/utils';

import { CoinData } from '@/interface';
import { TOKEN_SYMBOL } from '@/lib';

import { Network, OBJECT_RECORD } from '.';

export const COIN_METADATA = {
  [SUI_TYPE_ARG]: {
    name: 'Sui',
    decimals: 9,
    symbol: TOKEN_SYMBOL.SUI,
  },
};

export const TESTNET_BASE_COINS = {
  SUI: SUI_TYPE_ARG,
  BNB: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::ibnb::IBNB',
  ETH: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::ieth::IETH',
  BTC: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::ibtc::IBTC',
  USDT: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::iusdt::IUSDT',
  USDC: '0xb8656a09a489819f07c444cb4a4a61a3b482a5ea994fd71b0a643ffc1c2f2dd0::iusdc::IUSDC',
};

export const VOLATILE = {
  [Network.TESTNET]: `${
    OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
  }::curve::Volatile`,
  [Network.MAINNET]: `${
    OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
  }::curve::Volatile`,
};

export const STABLE = {
  [Network.TESTNET]: `${
    OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
  }::curve::Stable`,
  [Network.MAINNET]: `${
    OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
  }::curve::Stable`,
};

export const MAINNET_BASE_COINS = {
  SUI: SUI_TYPE_ARG,
  ETH_WORMHOLE_USDC:
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
  NATIVE_WORMHOLE_ETH:
    '0xaf8cd5edc19c4512f4259f0bee101a40d41ebed738ade5874359610ef8eeced5::coin::COIN',
  ETH_WORMHOLE_USDT:
    '0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c::coin::COIN',
  NATIVE_WORMHOLE_WBNB:
    '0xb848cce11ef3a8f62eccea6eb5b35a12c4c2b1ee1af7755d02d7bd6218e8226f::coin::COIN',
  NATIVE_WORMHOLE_WAVAX:
    '0x1e8b532cca6569cab9f9b9ebc73f8c13885012ade714729aa3b450e0339ac766::coin::COIN',
  NATIVE_WORMHOLE_WFTM:
    '0x6081300950a4f1e2081580e919c210436a1bed49080502834950d31ee55a2396::coin::COIN',
  NATIVE_WORMHOLE_CELO:
    '0xa198f3be41cda8c07b3bf3fee02263526e535d682499806979a111e88a5a8d0f::coin::COIN',
  NATIVE_WORMHOLE_WMATIC:
    '0xdbe380b13a6d0f5cdedd58de8f04625263f113b3f9db32b3e1983f49e2841676::coin::COIN',
  NATIVE_WORMHOLE_SOL:
    '0xb7844e289a8410e50fb3ca48d69eb9cf29e27d223ef90353fe1bd8e27ff8f3f8::coin::COIN',
  BSC_WORMHOLE_ADA:
    '0x4eac6573f65e7db5aea5a23e1335993a57e088dcd4aff7934059d9a6311d8655::coin::COIN',
  BSC_WORMHOLE_BTCB:
    '0x5cc7b6ed0ce0d43d08667793f6efe7a34d678a780755dc37ea8bfa8805f63327::coin::COIN',
  BSC_WORMHOLE_USDT:
    '0x603b488c87e0d1df64560a61418c87238d440a29ee39bbd757b0c92d38a35c7c::coin::COIN',
  BSC_WORMHOLE_USDC:
    '0x909cba62ce96d54de25bec9502de5ca7b4f28901747bbf96b76c2e63ec5f1cba::coin::COIN',
  BSC_WORMHOLE_ETH:
    '0x5029d5a94429a73b8036cd67192d9c5e09bbc2c0fee942d50075a9edba66744f::coin::COIN',
  BSC_WORMHOLE_FLOKI:
    '0xbcbbd5c23edf35fc279e21ebc129a1187dbfa5b086c63a8e7ff202865888b27b::coin::COIN',
  BSC_WORMHOLE_DOGE:
    '0xd399b358bd0e835000f6caa8c771a7d186499b6e62d413c2fd6cfed709689f28::coin::COIN',
  ETH_CELER_WETH:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_weth_coin::CELER_WETH_COIN',
  ETH_CELER_WBTC:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_wbtc_coin::CELER_WBTC_COIN',
  ETH_CELER_USDC:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_usdc_coin::CELER_USDC_COIN',
  ETH_CELER_USDT:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_usdt_coin::CELER_USDT_COIN',
};

export const COIN_TYPE = {
  [Network.TESTNET]: {
    ...TESTNET_BASE_COINS,
    V_LP_SUI_ETH: `${
      OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.TESTNET]}, ${TESTNET_BASE_COINS.SUI}, ${
      TESTNET_BASE_COINS.ETH
    }>`,
    V_LP_BTC_ETH: `${
      OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.TESTNET]}, ${TESTNET_BASE_COINS.BTC}, ${
      TESTNET_BASE_COINS.ETH
    }>`,
    V_LP_BNB_ETH: `${
      OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.TESTNET]}, ${TESTNET_BASE_COINS.BNB}, ${
      TESTNET_BASE_COINS.ETH
    }>`,
    V_LP_ETH_USDT: `${
      OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.TESTNET]}, ${TESTNET_BASE_COINS.ETH}, ${
      TESTNET_BASE_COINS.USDT
    }>`,
    V_LP_ETH_USDC: `${
      OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.TESTNET]}, ${TESTNET_BASE_COINS.ETH}, ${
      TESTNET_BASE_COINS.USDC
    }>`,
    S_LP_USDC_USDT: `${
      OBJECT_RECORD[Network.TESTNET].DEX_PACKAGE_ID
    }::core::LPCoin<${STABLE[Network.TESTNET]}, ${TESTNET_BASE_COINS.USDC}, ${
      TESTNET_BASE_COINS.USDT
    }>`,
    SUID: '0x02871464ed71b80969b32f2b23c981b085866485ba5368c0f59588fcc0dbce47::suid::SUID',
  },
  [Network.MAINNET]: {
    ...MAINNET_BASE_COINS,
    S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${STABLE[Network.MAINNET]}, ${
      MAINNET_BASE_COINS.ETH_WORMHOLE_USDC
    }, ${MAINNET_BASE_COINS.ETH_WORMHOLE_USDT}>`,
    V_LP_SUI_NATIVE_WORMHOLE_ETH: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.NATIVE_WORMHOLE_ETH
    }>`,
    V_LP_SUI_ETH_WORMHOLE_USDT: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.ETH_WORMHOLE_USDT
    }>`,
    V_LP_SUI_ETH_WORMHOLE_USDC: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.ETH_WORMHOLE_USDC
    }>`,
    V_LP_SUI_NATIVE_WORMHOLE_WBNB: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.NATIVE_WORMHOLE_WBNB
    }>`,
    V_LP_SUI_NATIVE_WORMHOLE_WMATIC: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.NATIVE_WORMHOLE_WMATIC
    }>`,
    V_LP_SUI_NATIVE_WORMHOLE_WFTM: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.NATIVE_WORMHOLE_WFTM
    }>`,
    V_LP_SUI_NATIVE_WORMHOLE_CELO: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.NATIVE_WORMHOLE_CELO
    }>`,
    V_LP_SUI_NATIVE_WORMHOLE_WAVAX: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.NATIVE_WORMHOLE_WAVAX
    }>`,
    V_LP_SUI_BSC_WORMHOLE_ADA: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.BSC_WORMHOLE_ADA
    }>`,
    V_LP_SUI_BSC_WORMHOLE_BTCB: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.BSC_WORMHOLE_BTCB
    }>`,
    V_LP_SUI_BSC_WORMHOLE_USDT: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.BSC_WORMHOLE_USDT
    }>`,
    S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${STABLE[Network.MAINNET]}, ${
      MAINNET_BASE_COINS.BSC_WORMHOLE_USDT
    }, ${MAINNET_BASE_COINS.BSC_WORMHOLE_USDC}>`,
    V_LP_SUI_BSC_WORMHOLE_USDC: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.BSC_WORMHOLE_USDC
    }>`,
    S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${STABLE[Network.MAINNET]}, ${
      MAINNET_BASE_COINS.ETH_WORMHOLE_USDC
    }, ${MAINNET_BASE_COINS.BSC_WORMHOLE_USDC}>`,
    V_LP_SUI_BSC_WORMHOLE_FLOKI: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.BSC_WORMHOLE_FLOKI
    }>`,
    V_LP_SUI_BSC_WORMHOLE_DOGE: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.BSC_WORMHOLE_DOGE
    }>`,
    V_LP_SUI_BSC_WORMHOLE_ETH: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.BSC_WORMHOLE_ETH
    }>`,
    V_LP_SUI_NATIVE_WORMHOLE_SOL: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.NATIVE_WORMHOLE_SOL
    }>`,
    V_LP_SUI_ETH_CELER_WETH: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.ETH_CELER_WETH
    }>`,
    V_LP_SUI_ETH_CELER_WBTC: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.ETH_CELER_WBTC
    }>`,
    V_LP_SUI_ETH_CELER_USDC: `${
      OBJECT_RECORD[Network.MAINNET].DEX_PACKAGE_ID
    }::core::LPCoin<${VOLATILE[Network.MAINNET]}, ${MAINNET_BASE_COINS.SUI}, ${
      MAINNET_BASE_COINS.ETH_CELER_USDC
    }>`,
  },
};

export const COIN_TYPE_TO_STABLE = {
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].BNB]: false,
    [COIN_TYPE[Network.TESTNET].ETH]: false,
    [COIN_TYPE[Network.TESTNET].BTC]: false,
    [COIN_TYPE[Network.TESTNET].USDT]: true,
    [COIN_TYPE[Network.TESTNET].USDC]: true,
    [COIN_TYPE[Network.TESTNET].SUI]: false,
    [COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH]: false,
    [COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH]: false,
    [COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH]: false,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT]: false,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC]: false,
    [COIN_TYPE[Network.TESTNET].SUID]: true,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]: false,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]: true,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]: true,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]: false,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]: true,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]: true,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]: false,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]: false,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT]: true,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDT]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WMATIC]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_CELO]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WAVAX]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ADA]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDT]: false,
    [COIN_TYPE[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC]: true,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC]: false,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC]: true,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH]: false,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL]: false,
  },
};

export const COIN_TYPE_TO_SYMBOL = {
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].BNB]: TOKEN_SYMBOL.BNB,
    [COIN_TYPE[Network.TESTNET].ETH]: TOKEN_SYMBOL.ETH,
    [COIN_TYPE[Network.TESTNET].BTC]: TOKEN_SYMBOL.BTC,
    [COIN_TYPE[Network.TESTNET].USDT]: TOKEN_SYMBOL.USDT,
    [COIN_TYPE[Network.TESTNET].USDC]: TOKEN_SYMBOL.USDC,
    [COIN_TYPE[Network.TESTNET].SUI]: TOKEN_SYMBOL.SUI,
    [COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH]: TOKEN_SYMBOL.V_LP_SUI_ETH,
    [COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH]: TOKEN_SYMBOL.V_LP_BTC_ETH,
    [COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH]: TOKEN_SYMBOL.V_LP_BNB_ETH,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT]: TOKEN_SYMBOL.V_LP_ETH_USDT,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC]: TOKEN_SYMBOL.V_LP_ETH_USDC,
    [COIN_TYPE[Network.TESTNET].SUID]: TOKEN_SYMBOL.SUID,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: TOKEN_SYMBOL.SUI,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]: TOKEN_SYMBOL.ETH,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]: TOKEN_SYMBOL.USDC,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]: TOKEN_SYMBOL.USDT,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]:
      TOKEN_SYMBOL.WORMHOLE_WBNB,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]:
      TOKEN_SYMBOL.WORMHOLE_WAVAX,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]:
      TOKEN_SYMBOL.WORMHOLE_WFTM,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]:
      TOKEN_SYMBOL.WORMHOLE_CELO,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL]: TOKEN_SYMBOL.WORMHOLE_SOL,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]:
      TOKEN_SYMBOL.WORMHOLE_WMATIC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]: TOKEN_SYMBOL.WORMHOLE_ADA,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]: TOKEN_SYMBOL.WORMHOLE_BTCB,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]: TOKEN_SYMBOL.WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]: TOKEN_SYMBOL.WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]: TOKEN_SYMBOL.WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]:
      TOKEN_SYMBOL.WORMHOLE_FLOKI,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]: TOKEN_SYMBOL.WORMHOLE_DOGE,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT]:
      TOKEN_SYMBOL.S_LP_WORMHOLE_USDC_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDT]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WBNB,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WMATIC]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WMATIC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_CELO]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_CELO,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WAVAX]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WAVAX,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ADA]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_ADA,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_BTCB,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDT]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC]:
      TOKEN_SYMBOL.S_LP_WORMHOLE_USDT_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC]:
      TOKEN_SYMBOL.S_LP_WORMHOLE_USDC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_FLOKI,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_DOGE,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_SOL,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC]: TOKEN_SYMBOL.ETH_CELER_WBTC,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDC]: TOKEN_SYMBOL.ETH_CELER_USDC,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WETH]: TOKEN_SYMBOL.ETH_CELER_WETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WBTC]:
      TOKEN_SYMBOL.V_LP_SUI_ETH_CELER_WBTC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WETH]:
      TOKEN_SYMBOL.V_LP_SUI_ETH_CELER_WETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_USDC]:
      TOKEN_SYMBOL.V_LP_SUI_ETH_CELER_USDC,
  },
};

export const COIN_DECIMALS = {
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].BTC]: 9,
    [COIN_TYPE[Network.TESTNET].ETH]: 9,
    [COIN_TYPE[Network.TESTNET].BNB]: 9,
    [COIN_TYPE[Network.TESTNET].USDT]: 9,
    [COIN_TYPE[Network.TESTNET].USDC]: 9,
    [COIN_TYPE[Network.TESTNET].SUI]: 9,
    [COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH]: 0,
    [COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH]: 0,
    [COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH]: 0,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT]: 0,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC]: 0,
    [COIN_TYPE[Network.TESTNET].S_LP_USDC_USDT]: 0,
    [COIN_TYPE[Network.TESTNET].SUID]: 9,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: 9,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]: 8,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]: 6,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]: 6,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]: 8,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDT]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WMATIC]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_CELO]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WAVAX]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ADA]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDT]: 0,
    [COIN_TYPE[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC]: 0,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL]: 0,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WETH]: 9,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC]: 8,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDC]: 6,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDT]: 6,
  },
};

export const COIN_POOL = {
  [Network.TESTNET]: {
    V_LP_SUI_ETH:
      '0x1e1e6373b648f604706c387c579626dc8dd145f9f4cea878f7b16e259c31bb5c',
    V_LP_BTC_ETH:
      '0xacf1a6af31efaae5e95dbc8e34fc91f8039b08708448ef8866f787fa43603b67',
    V_LP_BNB_ETH:
      '0x0ee8994563b3bd7d029641ca1d097dc53464d87cbf179c4e6fb5e7c23baf9209',
    V_LP_ETH_USDT:
      '0x8a28f9789f61d84398a5f2e66ac759a784f437c6b14c7b5cbc3d712528c3fb7b',
    V_LP_ETH_USDC:
      '0x2b8dda430b7cfa52482cde2d84390bf0496cf95c4a40579faa08479cfa381b81',
    S_LP_USDC_USDT:
      '0xb4196e35125f821ef22237e7991233ffc83c1fae1781f113967f04d18d9d7645',
  },
  [Network.MAINNET]: {
    S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT:
      '0x9b7ef251c98bf6990f70f45bfd012de5308483ae2fa0d8e39f559323baacf9ca',
    V_LP_SUI_NATIVE_WORMHOLE_ETH:
      '0x8f41de61cdc1ee379cadd7889dd588fcab62552e48959d027ba1d8839c027771',
    V_LP_SUI_ETH_WORMHOLE_USDT:
      '0x9fc77859750974b84b931d79acfc7116abde230b5dd2bb164331819561b90771',
    V_LP_SUI_ETH_WORMHOLE_USDC:
      '0x85e87655a47628098b5fc2e62d4926c6384e0430f2eae60cf9c692562b688702',
    V_LP_SUI_NATIVE_WORMHOLE_WBNB:
      '0x8fc0924fda0700bfa3c2a21a71ad02205547673c03bb4c131a6fa15831fec73f',
    V_LP_SUI_NATIVE_WORMHOLE_WMATIC:
      '0x877a542a5e9e8b5b71b5ff62d37774820fbb2230bea3bb9dec76e25e126e6268',
    V_LP_SUI_NATIVE_WORMHOLE_WFTM:
      '0xa8385d3ae4378c610d355085cf01e565ab5c8e3e80d27e32d7b2a93fad7af583',
    V_LP_SUI_NATIVE_WORMHOLE_CELO:
      '0x40ffe408f84b562677cfbdc2a081abc3618642d98d8208675dc42a87589a31dd',
    V_LP_SUI_NATIVE_WORMHOLE_WAVAX:
      '0xfadbbca64245714cbd22f85f0d74cdba0a595e585155a2e2223de6e69400c7d2',
    V_LP_SUI_BSC_WORMHOLE_ADA:
      '0x31186ba7ba3d79e78a21d8282987bae0f78230a755734440bad931a9b06b10f1',
    V_LP_SUI_BSC_WORMHOLE_BTCB:
      '0xd9856ab45adec800dfa7887815422ac8f55607baeeb4a08b86c5d0ebd6ce1ec7',
    V_LP_SUI_BSC_WORMHOLE_USDT:
      '0x7e735695049e3e1e14d86768da12d0465d3b37b797ff6f775bd76225e331d457',
    S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC:
      '0x8f6c873aa5f680390aae092c4c62e7a755d602a6492eefdc02122400cf34f7e2',
    V_LP_SUI_BSC_WORMHOLE_USDC:
      '0xb05544f109fc1f77e4dbdfd1c42ac1585c52f31984371c677c7a47674de2f8b3',
    S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC:
      '0x7ee34a0ffc65c89e07312928291e6a0bcc8628513c6f3faf32cc4b4d0815ba3a',
    V_LP_SUI_BSC_WORMHOLE_FLOKI:
      '0x2d5f55761fd1dfdbb078e8d1ed11e1b6a35e162577e8c09eba1cc656c297b6b7',
    V_LP_SUI_BSC_WORMHOLE_DOGE:
      '0x7fc6556f6dcbdc1e639154eb71d9364f21b0845e944a7c4de7cec11abe1e0554',
    V_LP_SUI_BSC_WORMHOLE_ETH:
      '0x4e66be98b0b6f560d9c9e6ac6845e43a87f7a0f7c22679da992963122616daa8',
    V_LP_SUI_NATIVE_WORMHOLE_SOL:
      '0xb5d8ff88e9093847d2bed1c11faa4884aa56f286e662c58f0e1a424939300a1c',
    V_LP_SUI_ETH_CELER_WETH:
      '0x6506cb8cdd7edac437822881ddfd178ad3a09066d83f505c87999b1e3f595210',
    V_LP_SUI_ETH_CELER_WBTC:
      '0x3604dcc9514a375d0d0a076fdde63ea8890ca59e00d105e52d4de7c32c09b621',
    V_LP_SUI_ETH_CELER_USDC:
      '0x148968a14fae894eb39397802c3dd1173a3851d239f5d71672a22fb5931d3658',
  },
};

export const POOL_IDS = {
  [Network.TESTNET]: [
    COIN_POOL[Network.TESTNET].V_LP_SUI_ETH,
    COIN_POOL[Network.TESTNET].V_LP_BTC_ETH,
    COIN_POOL[Network.TESTNET].V_LP_BNB_ETH,
    COIN_POOL[Network.TESTNET].V_LP_ETH_USDC,
    COIN_POOL[Network.TESTNET].V_LP_ETH_USDT,
    COIN_POOL[Network.TESTNET].S_LP_USDC_USDT,
  ],
  [Network.MAINNET]: [
    COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB,
    COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH,
    COIN_POOL[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH,
    COIN_POOL[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB,
    COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC,
    COIN_POOL[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC,
    COIN_POOL[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC,
    COIN_POOL[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC,
    COIN_POOL[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL,
    COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE,
    COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI,
    COIN_POOL[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT,
  ],
};

export const POOL_ID_MAP = {
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH]:
      COIN_POOL[Network.TESTNET].V_LP_SUI_ETH,
    [COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH]:
      COIN_POOL[Network.TESTNET].V_LP_BTC_ETH,
    [COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH]:
      COIN_POOL[Network.TESTNET].V_LP_BNB_ETH,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC]:
      COIN_POOL[Network.TESTNET].V_LP_ETH_USDC,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT]:
      COIN_POOL[Network.TESTNET].V_LP_ETH_USDT,
    [COIN_TYPE[Network.TESTNET].S_LP_USDC_USDT]:
      COIN_POOL[Network.TESTNET].S_LP_USDC_USDT,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB]:
      COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH]:
      COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH]:
      COIN_POOL[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB]:
      COIN_POOL[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC]:
      COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC]:
      COIN_POOL[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC]:
      COIN_POOL[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC]:
      COIN_POOL[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL]:
      COIN_POOL[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE]:
      COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI]:
      COIN_POOL[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT]:
      COIN_POOL[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT,
  },
};

export const COINS: Record<Network, Record<string, CoinData>> = {
  [Network.TESTNET]: {
    ETH: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].ETH],
      symbol: TOKEN_SYMBOL.ETH,
      type: COIN_TYPE[Network.TESTNET].ETH,
    },
    BTC: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].BTC],
      symbol: TOKEN_SYMBOL.BTC,
      type: COIN_TYPE[Network.TESTNET].BTC,
    },
    BNB: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].BNB],
      symbol: TOKEN_SYMBOL.BNB,
      type: COIN_TYPE[Network.TESTNET].BNB,
    },
    SUI: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].SUI],
      symbol: TOKEN_SYMBOL.SUI,
      type: COIN_TYPE[Network.TESTNET].SUI,
    },
    USDC: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].USDC],
      symbol: TOKEN_SYMBOL.USDC,
      type: COIN_TYPE[Network.TESTNET].USDC,
    },
    USDT: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].USDT],
      symbol: TOKEN_SYMBOL.USDT,
      type: COIN_TYPE[Network.TESTNET].USDT,
    },
    V_LP_SUI_ETH: {
      decimals:
        COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH],
      symbol: TOKEN_SYMBOL.V_LP_SUI_ETH,
      type: COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH,
    },
    V_LP_BTC_ETH: {
      decimals:
        COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH],
      symbol: TOKEN_SYMBOL.V_LP_BTC_ETH,
      type: COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH,
    },
    V_LP_BNB_ETH: {
      decimals:
        COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH],
      symbol: TOKEN_SYMBOL.V_LP_BNB_ETH,
      type: COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH,
    },
    V_LP_ETH_USDT: {
      decimals:
        COIN_DECIMALS[Network.TESTNET][
          COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT
        ],
      symbol: TOKEN_SYMBOL.V_LP_ETH_USDT,
      type: COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT,
    },
    V_LP_ETH_USDC: {
      decimals:
        COIN_DECIMALS[Network.TESTNET][
          COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC
        ],
      symbol: TOKEN_SYMBOL.V_LP_ETH_USDC,
      type: COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC,
    },
    S_LP_USDC_USDT: {
      decimals:
        COIN_DECIMALS[Network.TESTNET][
          COIN_TYPE[Network.TESTNET].S_LP_USDC_USDT
        ],
      symbol: TOKEN_SYMBOL.S_LP_USDC_USDT,
      type: COIN_TYPE[Network.TESTNET].S_LP_USDC_USDT,
    },
    SUID: {
      decimals: COIN_DECIMALS[Network.TESTNET][COIN_TYPE[Network.TESTNET].SUI],
      symbol: TOKEN_SYMBOL.SUID,
      type: COIN_TYPE[Network.TESTNET].SUID,
    },
  },
  [Network.MAINNET]: {
    SUI: {
      decimals: COIN_DECIMALS[Network.MAINNET][COIN_TYPE[Network.MAINNET].SUI],
      symbol: TOKEN_SYMBOL.SUI,
      type: COIN_TYPE[Network.MAINNET].SUI,
    },
    ETH_WORMHOLE_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_USDC,
      type: COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC,
    },
    NATIVE_WORMHOLE_ETH: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_ETH,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH,
    },
    ETH_WORMHOLE_USDT: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_USDT,
      type: COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT,
    },
    NATIVE_WORMHOLE_WBNB: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_WBNB,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB,
    },
    NATIVE_WORMHOLE_WAVAX: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_WAVAX,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX,
    },
    NATIVE_WORMHOLE_WFTM: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_WFTM,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM,
    },
    NATIVE_WORMHOLE_SOL: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_SOL,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL,
    },
    NATIVE_WORMHOLE_CELO: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_CELO,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO,
    },
    NATIVE_WORMHOLE_WMATIC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_WMATIC,
      type: COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC,
    },
    BSC_WORMHOLE_ADA: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_ADA,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA,
    },
    BSC_WORMHOLE_BTCB: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_BTCB,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB,
    },
    BSC_WORMHOLE_USDT: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_USDT,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT,
    },
    BSC_WORMHOLE_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_USDC,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC,
    },
    BSC_WORMHOLE_ETH: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_ETH,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH,
    },
    BSC_WORMHOLE_FLOKI: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_FLOKI,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI,
    },
    BSC_WORMHOLE_DOGE: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE
        ],
      symbol: TOKEN_SYMBOL.WORMHOLE_DOGE,
      type: COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE,
    },
    S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT
        ],
      symbol: TOKEN_SYMBOL.S_LP_USDC_USDT,
      type: COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT,
    },
    V_LP_SUI_NATIVE_WORMHOLE_ETH: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_ETH,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH,
    },
    V_LP_SUI_ETH_WORMHOLE_USDT: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDT
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDT,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDT,
    },
    V_LP_SUI_ETH_WORMHOLE_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDC,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC,
    },
    V_LP_SUI_NATIVE_WORMHOLE_WBNB: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WBNB,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB,
    },
    V_LP_SUI_NATIVE_WORMHOLE_WMATIC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WMATIC
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WMATIC,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WMATIC,
    },
    V_LP_SUI_NATIVE_WORMHOLE_WFTM: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WFTM
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WFTM,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WFTM,
    },
    V_LP_SUI_NATIVE_WORMHOLE_CELO: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_CELO
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_CELO,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_CELO,
    },
    V_LP_SUI_NATIVE_WORMHOLE_WAVAX: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WAVAX
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WAVAX,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WAVAX,
    },
    V_LP_SUI_BSC_WORMHOLE_ADA: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ADA
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_ADA,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ADA,
    },
    V_LP_SUI_BSC_WORMHOLE_BTCB: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_BTCB,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB,
    },
    V_LP_SUI_BSC_WORMHOLE_USDT: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDT
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDT,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDT,
    },
    S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC
        ],
      symbol: TOKEN_SYMBOL.S_LP_WORMHOLE_USDT_WORMHOLE_USDC,
      type: COIN_TYPE[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC,
    },
    V_LP_SUI_BSC_WORMHOLE_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDC,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC,
    },
    S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC
        ],
      symbol: TOKEN_SYMBOL.S_LP_WORMHOLE_USDC_WORMHOLE_USDC,
      type: COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC,
    },
    V_LP_SUI_BSC_WORMHOLE_FLOKI: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_FLOKI,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI,
    },
    V_LP_SUI_BSC_WORMHOLE_DOGE: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_DOGE,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE,
    },
    V_LP_SUI_BSC_WORMHOLE_ETH: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_ETH,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH,
    },
    V_LP_SUI_NATIVE_WORMHOLE_SOL: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_SOL,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL,
    },
    ETH_CELER_WBTC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC
        ],
      symbol: TOKEN_SYMBOL.ETH_CELER_WBTC,
      type: COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC,
    },
    ETH_CELER_WETH: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_CELER_WETH
        ],
      symbol: TOKEN_SYMBOL.ETH_CELER_WETH,
      type: COIN_TYPE[Network.MAINNET].ETH_CELER_WETH,
    },
    ETH_CELER_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].ETH_CELER_USDC
        ],
      symbol: TOKEN_SYMBOL.ETH_CELER_USDC,
      type: COIN_TYPE[Network.MAINNET].ETH_CELER_USDC,
    },
    V_LP_SUI_ETH_CELER_WBTC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WBTC
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_ETH_CELER_WBTC,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WBTC,
    },
    V_LP_SUI_ETH_CELER_WETH: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WETH
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_ETH_CELER_WETH,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WETH,
    },
    V_LP_SUI_ETH_CELER_USDC: {
      decimals:
        COIN_DECIMALS[Network.MAINNET][
          COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_USDC
        ],
      symbol: TOKEN_SYMBOL.V_LP_SUI_ETH_CELER_USDC,
      type: COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_USDC,
    },
  },
};

export const COIN_TYPE_TO_COIN = {
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].ETH]: COINS[Network.TESTNET].ETH,
    [COIN_TYPE[Network.TESTNET].BTC]: COINS[Network.TESTNET].BTC,
    [COIN_TYPE[Network.TESTNET].BNB]: COINS[Network.TESTNET].BNB,
    [COIN_TYPE[Network.TESTNET].SUI]: COINS[Network.TESTNET].SUI,
    [COIN_TYPE[Network.TESTNET].USDC]: COINS[Network.TESTNET].USDC,
    [COIN_TYPE[Network.TESTNET].USDT]: COINS[Network.TESTNET].USDT,
    [COIN_TYPE[Network.TESTNET].SUID]: COINS[Network.TESTNET].SUID,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: COINS[Network.MAINNET].SUI,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]:
      COINS[Network.MAINNET].ETH_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]:
      COINS[Network.MAINNET].ETH_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_SOL,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_WBNB,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_WAVAX,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_WFTM,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_CELO,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]:
      COINS[Network.MAINNET].NATIVE_WORMHOLE_WMATIC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]:
      COINS[Network.MAINNET].BSC_WORMHOLE_ADA,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]:
      COINS[Network.MAINNET].BSC_WORMHOLE_BTCB,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]:
      COINS[Network.MAINNET].BSC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]:
      COINS[Network.MAINNET].BSC_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]:
      COINS[Network.MAINNET].BSC_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]:
      COINS[Network.MAINNET].BSC_WORMHOLE_FLOKI,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]:
      COINS[Network.MAINNET].BSC_WORMHOLE_DOGE,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT]:
      COINS[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH]:
      COINS[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC]:
      COINS[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDT]:
      COINS[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB]:
      COINS[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WMATIC]:
      COINS[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WMATIC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_CELO]:
      COINS[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_CELO,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WAVAX]:
      COINS[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WAVAX,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ADA]:
      COINS[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ADA,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB]:
      COINS[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDT]:
      COINS[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC]:
      COINS[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC]:
      COINS[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC]:
      COINS[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI]:
      COINS[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE]:
      COINS[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH]:
      COINS[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL]:
      COINS[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WETH]:
      COINS[Network.MAINNET].ETH_CELER_WETH,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC]:
      COINS[Network.MAINNET].ETH_CELER_WBTC,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDC]:
      COINS[Network.MAINNET].ETH_CELER_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WETH]:
      COINS[Network.MAINNET].V_LP_SUI_ETH_CELER_WETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WBTC]:
      COINS[Network.MAINNET].V_LP_SUI_ETH_CELER_WBTC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_USDC]:
      COINS[Network.MAINNET].V_LP_SUI_ETH_CELER_USDC,
  },
};

export const STRICT_TOKENS: Record<Network, ReadonlyArray<string>> = {
  [Network.TESTNET]: [
    TESTNET_BASE_COINS.SUI,
    TESTNET_BASE_COINS.BNB,
    TESTNET_BASE_COINS.BTC,
    TESTNET_BASE_COINS.ETH,
    TESTNET_BASE_COINS.USDC,
    TESTNET_BASE_COINS.USDT,
  ],
  [Network.MAINNET]: [MAINNET_BASE_COINS.SUI],
};

export const WORMHOLE_TOKENS: Record<Network, ReadonlyArray<string>> = {
  [Network.TESTNET]: [],
  [Network.MAINNET]: [
    MAINNET_BASE_COINS.BSC_WORMHOLE_ADA,
    MAINNET_BASE_COINS.BSC_WORMHOLE_BTCB,
    MAINNET_BASE_COINS.BSC_WORMHOLE_DOGE,
    MAINNET_BASE_COINS.BSC_WORMHOLE_ETH,
    MAINNET_BASE_COINS.BSC_WORMHOLE_FLOKI,
    MAINNET_BASE_COINS.BSC_WORMHOLE_USDC,
    MAINNET_BASE_COINS.BSC_WORMHOLE_USDT,
    MAINNET_BASE_COINS.ETH_WORMHOLE_USDC,
    MAINNET_BASE_COINS.ETH_WORMHOLE_USDT,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_CELO,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_ETH,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_SOL,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_WAVAX,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_WBNB,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_WFTM,
    MAINNET_BASE_COINS.NATIVE_WORMHOLE_WMATIC,
  ],
};

export const CELER_TOKENS: Record<Network, ReadonlyArray<string>> = {
  [Network.TESTNET]: [],
  [Network.MAINNET]: [
    MAINNET_BASE_COINS.ETH_CELER_USDC,
    MAINNET_BASE_COINS.ETH_CELER_USDT,
    MAINNET_BASE_COINS.ETH_CELER_WBTC,
    MAINNET_BASE_COINS.ETH_CELER_WETH,
  ],
};

export const COINS_ADDITIONAL_INFO = {
  [SUI_TYPE_ARG]: {},
  ETH_WORMHOLE_USDC:
    '0x5d4b302506645c37ff133b98c4b50a5ae14841659738d6d733d59d0d217a93bf::coin::COIN',
  NATIVE_WORMHOLE_ETH:
    '0xaf8cd5edc19c4512f4259f0bee101a40d41ebed738ade5874359610ef8eeced5::coin::COIN',
  ETH_WORMHOLE_USDT:
    '0xc060006111016b8a020ad5b33834984a437aaa7d3c74c18e09a95d48aceab08c::coin::COIN',
  NATIVE_WORMHOLE_WBNB:
    '0xb848cce11ef3a8f62eccea6eb5b35a12c4c2b1ee1af7755d02d7bd6218e8226f::coin::COIN',
  NATIVE_WORMHOLE_WAVAX:
    '0x1e8b532cca6569cab9f9b9ebc73f8c13885012ade714729aa3b450e0339ac766::coin::COIN',
  NATIVE_WORMHOLE_WFTM:
    '0x6081300950a4f1e2081580e919c210436a1bed49080502834950d31ee55a2396::coin::COIN',
  NATIVE_WORMHOLE_CELO:
    '0xa198f3be41cda8c07b3bf3fee02263526e535d682499806979a111e88a5a8d0f::coin::COIN',
  NATIVE_WORMHOLE_WMATIC:
    '0xdbe380b13a6d0f5cdedd58de8f04625263f113b3f9db32b3e1983f49e2841676::coin::COIN',
  NATIVE_WORMHOLE_SOL:
    '0xb7844e289a8410e50fb3ca48d69eb9cf29e27d223ef90353fe1bd8e27ff8f3f8::coin::COIN',
  BSC_WORMHOLE_ADA:
    '0x4eac6573f65e7db5aea5a23e1335993a57e088dcd4aff7934059d9a6311d8655::coin::COIN',
  BSC_WORMHOLE_BTCB:
    '0x5cc7b6ed0ce0d43d08667793f6efe7a34d678a780755dc37ea8bfa8805f63327::coin::COIN',
  BSC_WORMHOLE_USDT:
    '0x603b488c87e0d1df64560a61418c87238d440a29ee39bbd757b0c92d38a35c7c::coin::COIN',
  BSC_WORMHOLE_USDC:
    '0x909cba62ce96d54de25bec9502de5ca7b4f28901747bbf96b76c2e63ec5f1cba::coin::COIN',
  BSC_WORMHOLE_ETH:
    '0x5029d5a94429a73b8036cd67192d9c5e09bbc2c0fee942d50075a9edba66744f::coin::COIN',
  BSC_WORMHOLE_FLOKI:
    '0xbcbbd5c23edf35fc279e21ebc129a1187dbfa5b086c63a8e7ff202865888b27b::coin::COIN',
  BSC_WORMHOLE_DOGE:
    '0xd399b358bd0e835000f6caa8c771a7d186499b6e62d413c2fd6cfed709689f28::coin::COIN',
  ETH_CELER_WETH:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_weth_coin::CELER_WETH_COIN',
  ETH_CELER_WBTC:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_wbtc_coin::CELER_WBTC_COIN',
  ETH_CELER_USDC:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_usdc_coin::CELER_USDC_COIN',
  ETH_CELER_USDT:
    '0x94e7a8e71830d2b34b3edaa195dc24c45d142584f06fa257b73af753d766e690::celer_usdt_coin::CELER_USDT_COIN',
};
