export const A_SECOND_IN_MILLISECONDS = 1000;
export const A_MINUTE_IN_MILLISECONDS = A_SECOND_IN_MILLISECONDS * 60;
export const A_HOUR_IN_MILLISECONDS = A_MINUTE_IN_MILLISECONDS * 60;
export const A_DAY_IN_MILLISECONDS = A_HOUR_IN_MILLISECONDS * 24;
export const A_WEEK_IN_MILLISECONDS = A_DAY_IN_MILLISECONDS * 7;
export const A_MONTH_IN_MILLISECONDS = A_DAY_IN_MILLISECONDS * 30;
