export { default as ComputerEyesSVG } from './computer-eyes';
export { default as DiedComputerSVG } from './died-computer';
export { default as DownArrowSVG } from './down-arrow';
export { default as ETHSVG } from './eth';
export { default as HeartSVG } from './heart';
export { default as LogoSVG } from './logo';
export { default as SwapArrowSVG } from './swap-arrow';
export { default as UnknownCoinSVG } from './unknown-coin';
export { default as USDCSVG } from './usdc';
